package com.example.demo.model;
// Generated 2023年4月13日 下午9:55:39 by Hibernate Tools 3.6.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreRemove;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerResponse generated by hbm2java
 */
@Entity
@Table(name = "customer_response", catalog = "pet_hotel_system")
public class CustomerResponse implements java.io.Serializable {

	private int id;
	private Users users;
	private OrderCommodity orderCommodity;
	private OrderRooms orderRooms;
	private String response;
	private Date createdAt;
	private Date updatedAt;
	
	@PrePersist
	protected void onCreate() {
	    createdAt = new Date();
	}

	@PreUpdate
	protected void onUpdate() {
	    updatedAt = new Date();
	}

	public CustomerResponse() {
	}

	public CustomerResponse(int id, Users users, Date createdAt) {
		this.id = id;
		this.users = users;
		this.createdAt = createdAt;
	}

	public CustomerResponse(int id, Users users, OrderCommodity orderCommodity, OrderRooms orderRooms, String response,
			Date createdAt, Date updatedAt) {
		this.id = id;
		this.users = users;
		this.orderCommodity = orderCommodity;
		this.orderRooms = orderRooms;
		this.response = response;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_commodity_id")
	public OrderCommodity getOrderCommodity() {
		return this.orderCommodity;
	}

	public void setOrderCommodity(OrderCommodity orderCommodity) {
		this.orderCommodity = orderCommodity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_room_id")
	public OrderRooms getOrderRooms() {
		return this.orderRooms;
	}

	public void setOrderRooms(OrderRooms orderRooms) {
		this.orderRooms = orderRooms;
	}

	@Column(name = "response", length = 300)
	public String getResponse() {
		return this.response;
	}

	public void setResponse(String response) {
		this.response = response;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
