package com.example.demo.model;
// Generated 2023年4月13日 下午9:55:39 by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import java.util.*;

/**
 * PermissionSet generated by hbm2java
 */
@Entity
@Table(name = "permission_set", catalog = "pet_hotel_system")
public class PermissionSet implements java.io.Serializable {

	private Integer id;
	private String tittleCn;
	private String tittleEn;
	private int memberMana;
	private int roomMana;
	private int commodityMana;
	private int workOrderMana;
	private int permissionMana;
	private List<Users> userses = new ArrayList<>();//修改除0

	public PermissionSet() {
	}

	public PermissionSet(String tittleCn, String tittleEn, int memberMana, int roomMana, int commodityMana,
			int workOrderMana, int permissionMana) {
		this.tittleCn = tittleCn;
		this.tittleEn = tittleEn;
		this.memberMana = memberMana;
		this.roomMana = roomMana;
		this.commodityMana = commodityMana;
		this.workOrderMana = workOrderMana;
		this.permissionMana = permissionMana;
	}

	public PermissionSet(String tittleCn, String tittleEn, int memberMana, int roomMana, int commodityMana,
			int workOrderMana, int permissionMana, List<Users> userses) {
		this.tittleCn = tittleCn;
		this.tittleEn = tittleEn;
		this.memberMana = memberMana;
		this.roomMana = roomMana;
		this.commodityMana = commodityMana;
		this.workOrderMana = workOrderMana;
		this.permissionMana = permissionMana;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tittle_cn", nullable = false, length = 45)
	public String getTittleCn() {
		return this.tittleCn;
	}

	public void setTittleCn(String tittleCn) {
		this.tittleCn = tittleCn;
	}

	@Column(name = "tittle_en", nullable = false, length = 45)
	public String getTittleEn() {
		return this.tittleEn;
	}

	public void setTittleEn(String tittleEn) {
		this.tittleEn = tittleEn;
	}

	@Column(name = "member_mana", nullable = false)
	public int getMemberMana() {
		return this.memberMana;
	}

	public void setMemberMana(int memberMana) {
		this.memberMana = memberMana;
	}

	@Column(name = "room_mana", nullable = false)
	public int getRoomMana() {
		return this.roomMana;
	}

	public void setRoomMana(int roomMana) {
		this.roomMana = roomMana;
	}

	@Column(name = "commodity_mana", nullable = false)
	public int getCommodityMana() {
		return this.commodityMana;
	}

	public void setCommodityMana(int commodityMana) {
		this.commodityMana = commodityMana;
	}

	@Column(name = "work_order_mana", nullable = false)
	public int getWorkOrderMana() {
		return this.workOrderMana;
	}

	public void setWorkOrderMana(int workOrderMana) {
		this.workOrderMana = workOrderMana;
	}

	@Column(name = "permission_mana", nullable = false)
	public int getPermissionMana() {
		return this.permissionMana;
	}

	public void setPermissionMana(int permissionMana) {
		this.permissionMana = permissionMana;
	}
																//修改，先去掉cascade = CascadeType.ALL
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permissionSet"/*,  cascade = CascadeType.ALL*/)
	public List<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(List<Users> userses) {
		this.userses = userses;
	}

}
