package com.example.demo.model;
// Generated 2023年4月13日 下午9:55:39 by Hibernate Tools 3.6.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreRemove;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoomSession generated by hbm2java
 */
@Entity
@Table(name = "room_session", catalog = "pet_hotel_system")
public class RoomSession implements java.io.Serializable {

	private Integer id;
	private Users users;
	private Rooms rooms;
	private OrderRooms orderRooms;
	private int attendType;
	private Date checkinTime;
	private String petNum;
	private String note;
	private Date reservationTime;
	private Date startDatetime;
	private Date endDatetime;
	private Date createdAt;
	private Date updatedAt;
	
	@PrePersist
	protected void onCreate() {
	    createdAt = new Date();
	}

	@PreUpdate
	protected void onUpdate() {
	    updatedAt = new Date();
	}

	public RoomSession() {
	}

	public RoomSession(Users users, Rooms rooms, int attendType, Date createdAt) {
		this.users = users;
		this.rooms = rooms;
		this.attendType = attendType;
		this.createdAt = createdAt;
	}

	public RoomSession(Users users, Rooms rooms, OrderRooms orderRooms, int attendType, Date checkinTime, String petNum, String note,
			Date reservationTime, Date startDatetime, Date endDatetime, Date createdAt, Date updatedAt) {
		this.users = users;
		this.rooms = rooms;
		this.orderRooms = orderRooms;
		this.attendType = attendType;
		this.checkinTime = checkinTime;
		this.petNum = petNum;
		this.note = note;
		this.reservationTime = reservationTime;
		this.startDatetime = startDatetime;
		this.endDatetime = endDatetime;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id", nullable = false)
	public Rooms getRooms() {
		return this.rooms;
	}

	public void setRooms(Rooms rooms) {
		this.rooms = rooms;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_room_id", nullable = false)
	public OrderRooms getOrderRooms() {
		return this.orderRooms;
	}

	public void setOrderRooms(OrderRooms orderRooms) {
		this.orderRooms = orderRooms;
	}

	@Column(name = "attend_type", nullable = false)
	public int getAttendType() {
		return this.attendType;
	}

	public void setAttendType(int attendType) {
		this.attendType = attendType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "checkin_time", length = 19)
	public Date getCheckinTime() {
		return this.checkinTime;
	}

	public void setCheckinTime(Date checkinTime) {
		this.checkinTime = checkinTime;
	}

	@Column(name = "pet_num", length = 45)
	public String getPetNum() {
		return this.petNum;
	}

	public void setPetNum(String petNum) {
		this.petNum = petNum;
	}

	@Column(name = "note", length = 45)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reservation_time", length = 19)
	public Date getReservationTime() {
		return this.reservationTime;
	}

	public void setReservationTime(Date reservationTime) {
		this.reservationTime = reservationTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_datetime", length = 19)
	public Date getStartDatetime() {
		return this.startDatetime;
	}

	public void setStartDatetime(Date startDatetime) {
		this.startDatetime = startDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_datetime", length = 19)
	public Date getEndDatetime() {
		return this.endDatetime;
	}

	public void setEndDatetime(Date endDatetime) {
		this.endDatetime = endDatetime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
